

[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aa_utilities"
version = "0.0.50"
description = "General utilities that I often use during my day-to-day work"
readme = "README.md"
authors = [{ name = "Amin Allahyar", email = "amin.allahyar@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["utilities", "personal"]
requires-python = ">=3.10"
dynamic = ["dependencies"]

[project.urls]
repository    = "https://github.com/aallahyar/aa_utilities.git"
documentation = "https://github.com/aallahyar/aa_utilities/blob/main/README.md"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}


[project.optional-dependencies]
# install with extras:
# pip3 install aa_utilities[extras]

extras = [
    "colorama", 
    "ipympl", # if interactive visualization is needed
    "statsmodels", # for expression level correction
    "patsy", # for expression level correction
    "rpy2>=3.5.15", # for R integration
    "joblib", # for parallelization of R calls
]

# pyproject.toml — pytest defaults (optional but recommended)
[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-ra" # show extra test summary info for skipped, failed, etc.
markers = [
    "requires_rspace: mark test as requiring R and rpy2",
]